### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by yeelali14**

### CODE REVIEW

**Review by yeelali14 — COMMENTED** [review]
test

**Review by royg-ermetic — COMMENTED** [review]
testttt

**Review by slowHand14 — COMMENTED** [review]
ljmk

**Comment by royg-ermetic** [comment]
fjgsgdf

Roy Grimberg  |  SRE Manager

e: ***@***.***  |  p: (+972)-54-725-2331

Find me on LinkedIn <https://www.linkedin.com/in/roy-grimberg-6606467a/>!

<http://www.ermetic.com>

**Review by slowHand14 — COMMENTED** [review]
mn,

**Comment by royg-ermetic** [comment]
correct

Roy Grimberg  |  SRE Manager

e: ***@***.***  |  p: (+972)-54-725-2331

Find me on LinkedIn <https://www.linkedin.com/in/roy-grimberg-6606467a/>!

<http://www.ermetic.com>

**Review by slowHand14 — COMMENTED** [review]
kjlj

**Review by slowHand14 — COMMENTED** [review]
creepy

**Pull request closed without merging**
